apiVersion: v1
kind: Service
metadata:
  name: nginx-pv
  labels:
    environment: dev
    owner: defo
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-nginx-pv
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-pv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx-pv
  template:
    metadata:
      labels:
        app: my-nginx-pv
    spec:
      volumes:
        - name: pv0001
          persistentVolumeClaim:
            claimName: pvc0001
      containers:
      - name: nginx
        image: fedora/nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: pv0001
            mountPath: "/usr/share/nginx/html"
            

