kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: IwwB3D7weLBoIHeNC3wMBEt9cH5MybSoRhUsSPp4vxk=
      - identity: {}
